### ISSUE TITLE
Ignore "arrays" when sync

### ISSUE THREAD

**Issue by Luddinus** [themsaid/laravel-langman#48] opened 2016-08-04 11:16 UTC
Hi,

I have this lang file e.g

```
// file lang/users.php
return [
   'tips' => [
      'one' => 'First tip',
      'two' => 'Second tip',
      // etc.
   ]
];
```

And in a controller or a file inside app directory:

```
// lang('users.tips') is an array
foreach (lang('users.tips') as $tip) {
   // do something with the texts
}
```

So the problem is that when I use "langman:sync" command, it writes an empty array in tips.

```
// file lang/users.php
return [
   'tips' => ''
];
```

Is this a bug or an expected behauvior?

Anyway, congrats for the package, it rocks.

**Comment by Luddinus** [comment] 2016-08-06 09:11
ping @themsaid

**Comment by themsaid** [comment] 2016-08-06 09:12
Woops, sorry didn't notice the issue except now :)

Thank for the report, it seems like a bug and I'll look into it today and get back to you :)

**Comment by Luddinus** [comment] 2016-08-09 09:24
Well, from now I'm doing a ugly trick.

I read that dynamic "trans" are ignored so I'm doing this:

```
$langTrick = '.tips';
foreach ('user'.$langTrick as $tip) {
   echo $tip;
}
```

**Comment by themsaid** [comment] 2016-08-23 17:58
The issue is now fixed :)

**Closed** 2016-08-23 17:58 UTC
