### ISSUE TITLE
Undefined offset: 1

### ISSUE THREAD

**Issue by vpratfr** [themsaid/laravel-langman#20] opened 2016-04-09 13:14 UTC
```
$ php artisan langman:missing
Looking for missing translations...

  [ErrorException]
  Undefined offset: 1
```

No idea why that happens. I got some vendor files and maybe some files are created in one language and not in the others.

**Comment by themsaid** [comment] 2016-04-09 13:22
hmm maybe that's the reason, will look at it an 30 minutes and get back to you. Thanks for your feedback, it's quite useful :)

I'm trying to make the package cover all the cases and make language files management as easy as possible, because in the current large project I'm working on managing translations became a nightmare.

**Comment by vpratfr** [comment] 2016-04-09 13:27
For instance, if I want to add a new language (italian for instance), I would basically create a new `it` subfolder, then run the sync command and that folder would be populated with the new translation files.

**Comment by themsaid** [comment] 2016-04-09 13:58
I just tested the case of having files existing in a language but not the other, running `langman:missing` actually creates a new file and asks you to fill the lines key by key.

Can you please share the structure of your language files? Or if possible can you do some debugging inside the `MissingCommand` and try to figure out where the problem is cause I can't replicate the issue here.

**Comment by themsaid** [comment] 2016-04-10 16:39
@vpratfr, still having the same troubles running the package?

**Comment by vpratfr** [comment] 2016-04-12 19:58
Same problem after updating.

**Comment by themsaid** [comment] 2016-04-12 20:00
I really need to know the cause of the issue, cause I've used langman in 4 projects till now with complicated localisation structure and it seem to work. Can you please try to track the issue in `Themsaid/Langman/Command/MissingCommand.php`?

**Comment by vpratfr** [comment] 2016-04-13 13:59
I'll try to, but I won't have time to do that until at least 1 or 2 weeks.

**Comment by themsaid** [comment] 2016-04-13 14:03
No worries, I'm going to close the issue for now then. Please feel free to open a ticket if the issue with more details by the time you check it out. Hopefully you catch the issue and open a PR :)

Thanks for your feedback.

**Comment by vpratfr** [comment] 2016-04-13 17:08
Pretty strange way to proceed to close an issue which is still happening?!

**Comment by themsaid** [comment] 2016-04-13 17:12
It's just that we're unable to re-create the issue on different installation and you won't be able to provide further details so I thought to close it until somebody else reports. Anyway it's no opened again :)

**Comment by vpratfr** [comment] 2016-04-17 07:39
Here is some more info about the Exception:

```
$ php artisan langman:sync -v
Reading translation keys from views...


  [ErrorException]
  Undefined offset: 1


Exception trace:
 () at vendor\themsaid\laravel-langman\src\Manager.php:64
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at vendor\themsaid\laravel-langman\src\Manager.php:64
 Themsaid\Langman\Manager->Themsaid\Langman\{closure}() at vendor\laravel\framework\src\Illuminate\Support\Collection.php:347
 Illuminate\Support\Collection->groupBy() at vendor\themsaid\laravel-langman\src\Manager.php:68
 Themsaid\Langman\Manager->files() at vendor\themsaid\laravel-langman\src\Commands\SyncCommand.php:53
 Themsaid\Langman\Commands\SyncCommand->handle() at n/a:n/a
 ...
```

**Comment by vpratfr** [comment] 2016-04-17 07:44
This happens for a file within vendor. At line 63 I do a `var_dump($file);` and here is the output:

```
object(Symfony\Component\Finder\SplFileInfo)#873 (4) {
  ["relativePath":"Symfony\Component\Finder\SplFileInfo":private]=>
  string(20) "vendor\log-viewer\en"
  ["relativePathname":"Symfony\Component\Finder\SplFileInfo":private]=>
  string(32) "vendor\log-viewer\en\general.php"
  ["pathName":"SplFileInfo":private]=>
  string(69) "C:\Dev\sites\ikastola\resources\lang\vendor\log-viewer\en\general.php"
  ["fileName":"SplFileInfo":private]=>
  string(11) "general.php"
}
```

The exception is thrown because $matches is an empty array and you are trying to return $matches[1] 

Here is what general.php looks like:

```
<?php

return [
    'all'  => 'All',
    'date' => 'Date',
];
```

**Comment by vpratfr** [comment] 2016-04-17 07:54
A fix for that regex is to remove is and replace the if statement by that:

```
            if (Str::contains($file->getPath(), 'vendor')) {
                $fileName = basename($file->getRealPath());
                $vendorName = basename(dirname($file->getPath()));

                return "{$vendorName}::{$fileName}";
            } else {
                return $fileName;
            }
```

**Comment by vpratfr** [comment] 2016-04-17 07:55
That last code seems to work (at least it runs, I did not check the output)

**Comment by themsaid** [comment] 2016-04-17 07:58
👍 can you open a PR for that fix?

**Comment by vpratfr** [comment] 2016-04-17 08:02
I prefer to let you test it properly, I will not have time to do that before quite some time. I actually forced myself to spend a few minutes at least trying to find where the issue was to help you fix it. 

I am running on Windows, that may be why your regex is not working.

The fix seems trivial, maybe mine is not proper as the function will return something like "log-viewer::general.php" (you may not want the .php ending in that return value)

**Comment by themsaid** [comment] 2016-04-17 08:03
Alright no problem, I'll look into a fix and release a patch once I have a couple of minutes. Thank you :)

**Comment by vpratfr** [comment] 2016-04-17 08:08
No problem. Sorry I can't contribute more with code, I wish my days were 48 hours long.

**Closed** 2016-04-17 15:54 UTC
